In [1]:
import time
import numpy as np 
from zmqRemoteApi import RemoteAPIClient

In [2]:
def degree_To_radian(degree):
    return (degree * np.pi/180)

def FK(theta, alfa, a, d):
    
    Cos_theta = np.cos(theta)
    Sin_theta = np.sin(theta)
    Cos_alfa = np.cos(alfa)
    Sin_alfa = np.sin(alfa)
    Transformation_mat = np.array([
                                    [Cos_theta,-Sin_theta*Cos_alfa,Sin_theta*Sin_alfa,a*Cos_theta],
                                    [Sin_theta,Cos_theta*Cos_alfa,-Cos_theta*Sin_alfa,a*Sin_theta],
                                    [0,Sin_alfa,Cos_alfa,d],
                                    [0,0,0,1]
                                  ])
    return np.round(Transformation_mat.reshape(4,4),2)

In [16]:
def Calculate_Jacopian_P(Trans_mat_arr):
    
    O_0 = np.zeros([3,1])
    Jp_size = len(Trans_mat_arr)
    Z_0 = np.array([[0,0,1]]).reshape(3,1)
    Z_arr = [z[0:3,2] for z in Trans_mat_arr]
    Z_arr.insert(0,Z_0)
    O_arr = [o[0:3,3] for o in Trans_mat_arr]
    O_arr.insert(0,O_0)
    O_last = O_arr[-1].reshape(3,1)
    jp_mat = np.array([
        [np.cross(Z_arr[i].reshape(3,1) , (O_last-O_arr[i].reshape(3,1)),axis=0) for i in range(Jp_size)]
    ])
    return jp_mat.reshape(3,Jp_size).transpose()
    
def Calculate_Jacopian_r(Trans_mat_arr):
    
    Z_0 = np.array([[0,0,1]])
    Jp_size = len(Trans_mat_arr)
    Z_arr = [Trans_mat_arr[z][0:3,2] for z in range(Jp_size-1)]
    Z_arr.insert(0,Z_0)
    Jr_mat = np.array([[z.reshape(3,1) for z in Z_arr]])
    return Jr_mat.reshape(3,Jp_size).transpose()

def Calculate_J(Trans_mat_arr):
    
    J_size = len(Trans_mat_arr)
    J = np.array([
                    [Calculate_Jacopian_P(Trans_mat_arr),
                     Calculate_Jacopian_r(Trans_mat_arr)]
                ])
    return J.reshape(6,J_size)

In [17]:
def Calculate_0n_Matrix(Trans_mat_arr):
    
    n = len(Trans_mat_arr)
    T_0 = np.identity(4)
    result_mat = []
    for i in range(n):
        T_0 = np.matmul(T_0,Trans_mat_arr[i])
        T_0 = np.round(T_0,2)
        result_mat.append( T_0 )
    return result_mat
    

In [18]:
def Calculate_Delta_X(Td, T0):
    
    Pd = Td[0:3,3]
    P0 = T0[0:3,3]
    Rd = Td[0:3,0:3]
    R0 = T0[0:3,0:3]
    I = np.identity(3)
    Pos_list = np.array([[d-c for d,c in zip(Pd,P0)]])
    Pos_list = Pos_list.reshape(3,1)
    DR = np.matmul(Rd,R0.transpose())
    skew = np.subtract(DR , I)
    skew = np.round(skew,2)
    print("skew = \n",skew)
    vec = np.array([[abs(skew[1,2]),abs(skew[0,2]) ,abs(skew[0,1])]])
    print("vec = \n",vec)
    vec = vec.reshape(3,1)
    Delta_X = np.array([Pos_list,vec])
    return np.round(Delta_X.reshape(6,1),2)  

In [19]:
def Calculate_IK(dX,J,q0):
    # qd = q0 + J+ * d_X
    j_pinv = np.linalg.pinv(J)
    q0_arr = np.array([q0])
    q0_arr = q0_arr.reshape(6,1)
    qd = np.add(q0_arr,np.matmul(np.round(j_pinv,2),dX)) # 6*1
    return np.round(qd.reshape(1,6),2)

In [20]:
client = RemoteAPIClient()
sim = client.getObject('sim')
# When simulation is not running, ZMQ message handling could be a bit
# slow, since the idle loop runs at 8 Hz by default. So let's make
# sure that the idle loop runs at full speed for this program:
defaultIdleFps = sim.getInt32Param(sim.intparam_idle_fps)
sim.setInt32Param(sim.intparam_idle_fps, 0)

1

In [21]:
# set Object name 
joint_names = [f"joint_{i+1}"  for i in range(6)]

joint_handels = [sim.getObjectHandle(joint) for joint in joint_names]
# set Object handel 
EE_handle = sim.getObjectHandle("EE_h")
EE_h_Pos = sim.getObjectPosition(EE_handle,joint_handels[0])


joint_Position = [sim.getJointPosition(handle) for handle in joint_handels]

joint_6_pos = sim.getObjectPosition(joint_handels[-1],joint_handels[0] )

joint_6_pos = np.round(joint_6_pos,2)

# T0
EE_Trans = np.array([ sim.getObjectMatrix( EE_handle ,joint_handels[0]) ])
EE_Trans = np.round(EE_Trans.reshape(3,4),2)

Target_handle = sim.getObjectHandle("Cuboid")

# print("joint_Position = \n",np.round(joint_Position,2))
# print("EE_Trans = \n",np.round(EE_Trans.reshape(3,4),2))
# print("EE_h_Pos = \n",np.round(EE_h_Pos,2))

for handle in joint_handels:
    sim.setObjectInt32Parameter(handle ,2001,~0) #to enable the position control

In [22]:
# init DH-parameters
q0 = [0,0,0,0,0,0]
alpha = [90,0,0,90,-90,0]
D = [0.1519,0,0,0.11235,0.08535,0.0819]
A = [0,-0.24365,-0.21325,0,0,0]


In [23]:
# calc Transformation matrix using FK
Trans_list = [FK(degree_To_radian(q0[i]),degree_To_radian(alpha[i]),A[i],D[i]) for i in range(6)]

T_0n = Calculate_0n_Matrix(Trans_list)

# T_0n = [ np.array([ sim.getObjectMatrix(joint_handels[i],joint_handels[0] )]).reshape(3,4) for i in range(1,6)]

# T_0n.insert(0,np.array([ sim.getObjectMatrix( joint_handels[0] , -1 ) ]).reshape(3,4) )

# for i in range(6):
#      T_0n[i] = np.round(T_0n[i],2)

# print("qd = \n",qd,"\n\n")
print("T_0n[5] = \n",T_0n[-1],"\n\n")
print("EE_Trans = \n",EE_Trans,"\n\n")
print("EE_h_Pos = \n",np.round(EE_h_Pos,2),"\n\n")
print("joint_6_pos = \n",joint_6_pos)
print("t00 = \n",T_0n[0])
# print("delta_X = \n",delta_X)

# for t in Trans_list:
#     print("t = \n",t,"\n")

# calc T disierd
# T_d = FK(degree_To_radian(30),degree_To_radian(45),0,0)
T_d = np.array([ sim.getObjectMatrix( Target_handle ,-1)])
T_d = T_d.reshape(3,4)
T0_6 = EE_Trans

T_0n[5] = 
 [[ 1.    0.    0.   -0.45]
 [ 0.    0.   -1.   -0.19]
 [ 0.    1.    0.    0.06]
 [ 0.    0.    0.    1.  ]] 


EE_Trans = 
 [[ 0.    1.    0.   -0.  ]
 [ 0.   -0.    1.    0.19]
 [ 1.   -0.    0.    0.55]] 


EE_h_Pos = 
 [-0.    0.19  0.55] 


joint_6_pos = 
 [-0.    0.11  0.55]
t00 = 
 [[ 1.    0.    0.    0.  ]
 [ 0.    0.   -1.    0.  ]
 [ 0.    1.    0.    0.15]
 [ 0.    0.    0.    1.  ]]


In [24]:
# claculate Jacopian matrix
J = Calculate_J(T_0n)

# calculate delta X matrix  
delta_X = Calculate_Delta_X(T_d,EE_Trans)

print("delta_X = \n ",delta_X)

# calculate qd using IK 
qd = Calculate_IK(delta_X,J,q0)

print(qd)

print("np.linalg.norm(delta_X) =",np.round(np.linalg.norm(delta_X),2))

# print("np.linalg.norm(delta_X) = \n",np.round(np.linalg.norm(delta_X),2))

Jp_size =  6
skew = 
 [[-1.  0.  1.]
 [ 1. -1.  0.]
 [ 0.  1. -1.]]
vec = 
 [[0. 1. 0.]]
delta_X = 
  [[ 0.2 ]
 [ 0.66]
 [-0.3 ]
 [ 0.  ]
 [ 1.  ]
 [ 0.  ]]
[[ 1.96 -2.88  0.93  0.17  0.    0.  ]]
np.linalg.norm(delta_X) = 1.25


In [25]:
while ~( np.isclose( np.linalg.norm(delta_X),0.1 ,rtol=0.01)  ):
    
    q0 = qd.copy()
    Trans_list.clear()
    Trans_list = [FK(q0[0][i],degree_To_radian(alpha[i]),A[i],D[i]) for i in range(6)]
    #Trans_list = [FK(theta,degree_To_radian(alp),a,d) for theta,alp,d,a in zip(q0[0],alpha,D,A)]
    T_0n = Calculate_0n_Matrix(Trans_list)

#     T_0n.clear()
#     T_0n = [ np.array([ sim.getObjectMatrix(joint_handels[i],joint_handels[0] )]).reshape(3,4) for i in range(1,6)]
#     T_0n.insert(0,np.array([ sim.getObjectMatrix( joint_handels[0] , -1 ) ]).reshape(3,4) )
    J = Calculate_J(T_0n)
    delta_X = Calculate_Delta_X(T_d,T_0n[-1])
    
    print("delta_X = \n",delta_X)
    print("np.linalg.norm(delta_X) =",np.round(np.linalg.norm(delta_X),2))
    
    qd = Calculate_IK(delta_X,J,q0)
    print("qd = \n",qd,"\n\n")    

Jp_size =  6
skew = 
 [[-0.92 -0.2  -0.98]
 [-0.38 -0.09 -0.21]
 [ 0.93  0.38 -1.  ]]
vec = 
 [[0.21 0.98 0.2 ]]
delta_X = 
 [[ 0.12]
 [ 0.56]
 [-0.18]
 [ 0.21]
 [ 0.98]
 [ 0.2 ]]
np.linalg.norm(delta_X) = 1.19
qd = 
 [[-31.21 -12.57  44.32 -26.16  31.93  21.32]] 


Jp_size =  6
skew = 
 [[-1.2   0.35  0.91]
 [-0.95 -0.89 -0.25]
 [-0.19 -0.93 -0.69]]
vec = 
 [[0.25 0.91 0.35]]
delta_X = 
 [[0.7 ]
 [1.13]
 [0.22]
 [0.25]
 [0.91]
 [0.35]]
np.linalg.norm(delta_X) = 1.68
qd = 
 [[-26.95 -16.46  46.06 -25.97  28.78  28.83]] 


Jp_size =  6
skew = 
 [[-1.17  0.97  0.1 ]
 [ 0.25 -1.06  0.96]
 [ 0.94  0.2  -1.23]]
vec = 
 [[0.96 0.1  0.97]]
delta_X = 
 [[0.27]
 [0.98]
 [0.  ]
 [0.96]
 [0.1 ]
 [0.97]]
np.linalg.norm(delta_X) = 1.7
qd = 
 [[ -4.23 -31.84  19.39 -38.71  21.78   9.08]] 


Jp_size =  6
skew = 
 [[-1.56  0.65 -0.5 ]
 [ 0.18 -1.51 -0.84]
 [-0.81 -0.57 -0.84]]
vec = 
 [[0.84 0.5  0.65]]
delta_X = 
 [[-0.07]
 [ 1.3 ]
 [ 0.08]
 [ 0.84]
 [ 0.5 ]
 [ 0.65]]
np.linalg.norm(delta_X) = 1.75
q

qd = 
 [[  178.62 -1203.62  -571.08   161.94  -472.22  4684.33]] 


Jp_size =  6
skew = 
 [[-1.03  0.92 -0.4 ]
 [-0.82 -0.79  0.54]
 [ 0.58  0.35 -0.25]]
vec = 
 [[0.54 0.4  0.92]]
delta_X = 
 [[0.56]
 [0.49]
 [0.02]
 [0.54]
 [0.4 ]
 [0.92]]
np.linalg.norm(delta_X) = 1.36
qd = 
 [[  177.44 -1201.91  -568.8    161.83  -470.19  4683.86]] 


Jp_size =  6
skew = 
 [[-1.87 -0.31  0.41]
 [-0.25 -1.46 -0.87]
 [ 0.45 -0.85 -0.68]]
vec = 
 [[0.87 0.41 0.31]]
delta_X = 
 [[0.06]
 [0.99]
 [0.1 ]
 [0.87]
 [0.41]
 [0.31]]
np.linalg.norm(delta_X) = 1.42
qd = 
 [[  184.68 -1207.58  -575.06   167.34  -481.5   4668.52]] 


Jp_size =  6
skew = 
 [[-0.14  0.25  0.43]
 [-0.49 -0.72  0.82]
 [ 0.08 -0.92 -0.63]]
vec = 
 [[0.82 0.43 0.25]]
delta_X = 
 [[0.04]
 [0.89]
 [0.13]
 [0.82]
 [0.43]
 [0.25]]
np.linalg.norm(delta_X) = 1.32
qd = 
 [[  162.51 -1197.12  -613.92   174.6   -497.65  4597.24]] 


Jp_size =  6
skew = 
 [[-1.44 -0.16  0.89]
 [ 0.38 -0.14  0.35]
 [-0.82  0.49 -1.32]]
vec = 
 [[0.35 0.89 0.16]]


qd = 
 [[  721.77 -1320.03 -1862.24   620.47  1516.14  4949.46]] 


Jp_size =  6
skew = 
 [[-0.24 -0.61  0.21]
 [-0.54 -1.78 -0.3 ]
 [ 0.35  0.11 -1.94]]
vec = 
 [[0.3  0.21 0.61]]
delta_X = 
 [[0.19]
 [0.98]
 [0.  ]
 [0.3 ]
 [0.21]
 [0.61]]
np.linalg.norm(delta_X) = 1.23
qd = 
 [[  719.87 -1320.83 -1851.04   612.74  1524.89  4952.13]] 


Jp_size =  6
skew = 
 [[-1.54 -0.84 -0.06]
 [-0.74 -0.49 -0.45]
 [ 0.4  -0.19 -1.9 ]]
vec = 
 [[0.45 0.06 0.84]]
delta_X = 
 [[0.01]
 [0.67]
 [0.09]
 [0.45]
 [0.06]
 [0.84]]
np.linalg.norm(delta_X) = 1.17
qd = 
 [[  721.64 -1324.27 -1852.63   612.06  1526.3   4949.85]] 


Jp_size =  6
skew = 
 [[-1.41  0.77 -0.5 ]
 [ 0.67 -1.11 -0.73]
 [-0.62 -0.63 -1.47]]
vec = 
 [[0.73 0.5  0.77]]
delta_X = 
 [[0.3 ]
 [1.01]
 [0.56]
 [0.73]
 [0.5 ]
 [0.77]]
np.linalg.norm(delta_X) = 1.67
qd = 
 [[  721.52 -1323.75 -1853.06   616.2   1522.76  4948.27]] 


Jp_size =  6
skew = 
 [[-0.59  0.84  0.38]
 [ 0.01 -1.41  0.92]
 [ 0.92 -0.37 -1.17]]
vec = 
 [[0.92 0.38 0.84]]


qd = 
 [[  718.99 -1272.45 -1255.53   570.36  1351.64  3204.76]] 


Jp_size =  6
skew = 
 [[-0.04  0.27 -0.04]
 [ 0.04 -1.26 -0.96]
 [-0.27  0.93 -1.27]]
vec = 
 [[0.96 0.04 0.27]]
delta_X = 
 [[ 0.53]
 [ 0.52]
 [-0.11]
 [ 0.96]
 [ 0.04]
 [ 0.27]]
np.linalg.norm(delta_X) = 1.25
qd = 
 [[  721.72 -1271.35 -1266.56   570.57  1352.41  3178.69]] 


Jp_size =  6
skew = 
 [[-1.84 -0.3  -0.46]
 [-0.06 -1.78  0.61]
 [-0.54  0.54 -0.35]]
vec = 
 [[0.61 0.46 0.3 ]]
delta_X = 
 [[0.39]
 [0.8 ]
 [0.03]
 [0.61]
 [0.46]
 [0.3 ]]
np.linalg.norm(delta_X) = 1.21
qd = 
 [[  697.96 -1275.03 -1268.83   572.38  1338.97  3153.17]] 


Jp_size =  6
skew = 
 [[-0.07  0.16  0.32]
 [-0.13 -1.67  0.74]
 [ 0.33 -0.73 -1.6 ]]
vec = 
 [[0.74 0.32 0.16]]
delta_X = 
 [[0.35]
 [1.14]
 [0.43]
 [0.74]
 [0.32]
 [0.16]]
np.linalg.norm(delta_X) = 1.51
qd = 
 [[  762.09 -1293.02 -1195.91   597.    1309.54  2998.03]] 


Jp_size =  6
skew = 
 [[-0.75  0.18  0.96]
 [-0.61 -0.19  0.  ]
 [-0.76 -0.58 -0.69]]
vec = 
 [[0.   0.96 0

skew = 
 [[-0.06  0.34  0.01]
 [ 0.07 -1.17 -0.98]
 [-0.33  0.91 -1.19]]
vec = 
 [[0.98 0.01 0.34]]
delta_X = 
 [[0.1 ]
 [0.78]
 [0.18]
 [0.98]
 [0.01]
 [0.34]]
np.linalg.norm(delta_X) = 1.31
qd = 
 [[  864.38 -1741.75  -468.26  2561.5  -1592.25  1053.07]] 


Jp_size =  6
skew = 
 [[-1.56  0.19 -0.8 ]
 [ 0.81 -0.94 -0.57]
 [-0.06 -0.98 -1.18]]
vec = 
 [[0.57 0.8  0.19]]
delta_X = 
 [[0.19]
 [0.8 ]
 [0.16]
 [0.57]
 [0.8 ]
 [0.19]]
np.linalg.norm(delta_X) = 1.3
qd = 
 [[  844.01 -1720.51  -505.56  2577.64 -1604.89  1259.4 ]] 


Jp_size =  6
skew = 
 [[-1.05  0.98  0.11]
 [ 0.13 -0.88 -0.98]
 [-0.99 -0.04 -1.13]]
vec = 
 [[0.98 0.11 0.98]]
delta_X = 
 [[0.15]
 [0.87]
 [0.21]
 [0.98]
 [0.11]
 [0.98]]
np.linalg.norm(delta_X) = 1.66
qd = 
 [[  840.9  -1716.28  -515.45  2573.27 -1607.99  1259.02]] 


Jp_size =  6
skew = 
 [[-0.77  0.3  -0.92]
 [ 0.76 -1.66 -0.02]
 [-0.61 -0.69 -1.37]]
vec = 
 [[0.02 0.92 0.3 ]]
delta_X = 
 [[ 0.42]
 [ 0.83]
 [-0.32]
 [ 0.02]
 [ 0.92]
 [ 0.3 ]]
np.linalg.norm(

skew = 
 [[-0.33  0.45 -0.59]
 [-0.45 -0.12  0.18]
 [ 0.6   0.13 -0.2 ]]
vec = 
 [[0.18 0.59 0.45]]
delta_X = 
 [[0.07]
 [0.98]
 [0.11]
 [0.18]
 [0.59]
 [0.45]]
np.linalg.norm(delta_X) = 1.25
qd = 
 [[ 1010.08 -2025.95  -628.57  2007.48  -953.18   799.65]] 


Jp_size =  6
skew = 
 [[-0.89  0.1   0.98]
 [ 0.97 -1.24 -0.07]
 [ 0.23  0.97 -1.12]]
vec = 
 [[0.07 0.98 0.1 ]]
delta_X = 
 [[0.27]
 [1.23]
 [0.08]
 [0.07]
 [0.98]
 [0.1 ]]
np.linalg.norm(delta_X) = 1.6
qd = 
 [[ 1006.8  -2016.88  -636.11  2007.98  -965.36   734.98]] 


Jp_size =  6
skew = 
 [[-0.19  0.4  -0.44]
 [ 0.05 -1.79 -0.62]
 [-0.6   0.48 -1.66]]
vec = 
 [[0.62 0.44 0.4 ]]
delta_X = 
 [[ 0.15]
 [ 0.99]
 [-0.1 ]
 [ 0.62]
 [ 0.44]
 [ 0.4 ]]
np.linalg.norm(delta_X) = 1.32
qd = 
 [[ 1060.12 -2028.78  -609.65  1939.08  -955.72   748.59]] 


Jp_size =  6
skew = 
 [[-0.7  -0.63 -0.72]
 [-0.62 -1.7   0.36]
 [-0.73  0.34 -1.59]]
vec = 
 [[0.36 0.72 0.63]]
delta_X = 
 [[0.3 ]
 [0.35]
 [0.37]
 [0.36]
 [0.72]
 [0.63]]
np.linalg.norm(

skew = 
 [[-0.29 -0.24 -0.67]
 [-0.47 -0.42 -0.68]
 [ 0.55  0.79 -0.7 ]]
vec = 
 [[0.68 0.67 0.24]]
delta_X = 
 [[-0.06]
 [ 0.71]
 [-0.18]
 [ 0.68]
 [ 0.67]
 [ 0.24]]
np.linalg.norm(delta_X) = 1.23
qd = 
 [[ 1296.47 -1623.3   -766.68  1888.51  -957.82   247.22]] 


Jp_size =  6
skew = 
 [[-0.53 -0.36  0.8 ]
 [-0.18 -0.14  0.49]
 [-0.86 -0.37 -0.67]]
vec = 
 [[0.49 0.8  0.36]]
delta_X = 
 [[ 0.38]
 [ 0.49]
 [-0.24]
 [ 0.49]
 [ 0.8 ]
 [ 0.36]]
np.linalg.norm(delta_X) = 1.2
qd = 
 [[ 1296.11 -1620.75  -766.4   1887.59  -957.56   245.1 ]] 


Jp_size =  6
skew = 
 [[-1.74  0.68 -0.09]
 [ 0.05 -1.09 -0.99]
 [-0.68 -0.74 -0.98]]
vec = 
 [[0.99 0.09 0.68]]
delta_X = 
 [[0.05]
 [1.31]
 [0.17]
 [0.99]
 [0.09]
 [0.68]]
np.linalg.norm(delta_X) = 1.79
qd = 
 [[ 1299.46 -1624.65  -766.71  1886.83  -940.45   272.99]] 


Jp_size =  6
skew = 
 [[-0.14  0.17 -0.49]
 [-0.11 -0.01  0.15]
 [ 0.51 -0.08 -0.14]]
vec = 
 [[0.15 0.49 0.17]]
delta_X = 
 [[0.13]
 [1.18]
 [0.23]
 [0.15]
 [0.49]
 [0.17]]
np.linalg

qd = 
 [[ 1036.35 -1731.61  -539.94  2035.15 -1101.64  -345.  ]] 


Jp_size =  6
skew = 
 [[-0.81  0.72 -0.68]
 [-0.91 -1.14 -0.41]
 [-0.39  0.68 -0.38]]
vec = 
 [[0.41 0.68 0.72]]
delta_X = 
 [[-0.18]
 [ 1.07]
 [ 0.17]
 [ 0.41]
 [ 0.68]
 [ 0.72]]
np.linalg.norm(delta_X) = 1.53
qd = 
 [[ 1038.14 -1728.63  -538.94  2035.47 -1104.65  -337.78]] 


Jp_size =  6
skew = 
 [[-1.   -0.36  0.94]
 [-0.98 -1.21 -0.07]
 [ 0.23 -0.91 -1.33]]
vec = 
 [[0.07 0.94 0.36]]
delta_X = 
 [[0.12]
 [1.25]
 [0.17]
 [0.07]
 [0.94]
 [0.36]]
np.linalg.norm(delta_X) = 1.62
qd = 
 [[ 1051.92 -1736.16  -544.52  2037.66 -1127.68  -326.49]] 


Jp_size =  6
skew = 
 [[-1.26 -0.01 -0.95]
 [ 0.86 -1.45 -0.22]
 [-0.43 -0.89 -0.87]]
vec = 
 [[0.22 0.95 0.01]]
delta_X = 
 [[ 0.16]
 [ 0.83]
 [-0.15]
 [ 0.22]
 [ 0.95]
 [ 0.01]]
np.linalg.norm(delta_X) = 1.3
qd = 
 [[ 1052.12 -1736.16  -543.97  2041.4  -1128.2   -323.99]] 


Jp_size =  6
skew = 
 [[-1.9  -0.06  0.42]
 [-0.4  -1.01 -0.91]
 [ 0.05 -0.99 -1.01]]
vec = 
 [[0.91 0

skew = 
 [[-0.3   0.5  -0.5 ]
 [ 0.57 -0.95  0.82]
 [ 0.44 -0.85 -1.24]]
vec = 
 [[0.82 0.5  0.5 ]]
delta_X = 
 [[ 0.27]
 [ 1.29]
 [-0.03]
 [ 0.82]
 [ 0.5 ]
 [ 0.5 ]]
np.linalg.norm(delta_X) = 1.71
qd = 
 [[  464.59 -1512.     902.11  1928.81 -1263.82 -2015.41]] 


Jp_size =  6
skew = 
 [[-0.45 -0.14  0.83]
 [-0.74 -1.54  0.39]
 [ 0.4  -0.82 -1.41]]
vec = 
 [[0.39 0.83 0.14]]
delta_X = 
 [[0.3 ]
 [0.98]
 [0.31]
 [0.39]
 [0.83]
 [0.14]]
np.linalg.norm(delta_X) = 1.42
qd = 
 [[  467.77 -1520.68   907.32  1924.26 -1263.3  -2013.72]] 


Jp_size =  6
skew = 
 [[-1.43  0.54  0.74]
 [ 0.74 -1.27  0.63]
 [ 0.53  0.81 -1.28]]
vec = 
 [[0.63 0.74 0.54]]
delta_X = 
 [[-0.02]
 [ 0.74]
 [ 0.17]
 [ 0.63]
 [ 0.74]
 [ 0.54]]
np.linalg.norm(delta_X) = 1.35
qd = 
 [[  460.4  -1513.89   912.51  1923.11 -1265.92 -2002.59]] 


Jp_size =  6
skew = 
 [[-0.83 -0.85 -0.49]
 [ 0.22 -1.46  0.85]
 [-0.96 -0.25 -0.89]]
vec = 
 [[0.85 0.49 0.85]]
delta_X = 
 [[0.15]
 [0.96]
 [0.33]
 [0.85]
 [0.49]
 [0.85]]
np.linal

qd = 
 [[-1379.5  -1310.06 -2725.04 -2713.98  2575.03 -5535.24]] 


Jp_size =  6
skew = 
 [[-1.72 -0.64 -0.24]
 [-0.61 -0.56  0.67]
 [-0.33  0.62 -1.72]]
vec = 
 [[0.67 0.24 0.64]]
delta_X = 
 [[0.3 ]
 [0.66]
 [0.01]
 [0.67]
 [0.24]
 [0.64]]
np.linalg.norm(delta_X) = 1.2
qd = 
 [[-1421.26 -1325.07 -2747.17 -2717.43  2572.12 -5629.31]] 


Jp_size =  6
skew = 
 [[-1.58 -0.4  -0.7 ]
 [ 0.04 -0.16 -0.53]
 [ 0.81 -0.34 -1.48]]
vec = 
 [[0.53 0.7  0.4 ]]
delta_X = 
 [[0.33]
 [0.63]
 [0.08]
 [0.53]
 [0.7 ]
 [0.4 ]]
np.linalg.norm(delta_X) = 1.2
qd = 
 [[-1405.64 -1353.63 -2775.58 -2715.16  2586.1  -5601.66]] 


Jp_size =  6
skew = 
 [[-0.45 -0.02 -0.83]
 [ 0.32 -1.92  0.23]
 [-0.78 -0.39 -1.5 ]]
vec = 
 [[0.23 0.83 0.02]]
delta_X = 
 [[ 0.16]
 [ 0.8 ]
 [-0.18]
 [ 0.23]
 [ 0.83]
 [ 0.02]]
np.linalg.norm(delta_X) = 1.2
qd = 
 [[-1405.22 -1362.3  -2769.03 -2722.15  2583.92 -5610.43]] 


Jp_size =  6
skew = 
 [[-0.02  0.19  0.08]
 [ 0.19 -1.98  0.07]
 [ 0.1  -0.06 -2.  ]]
vec = 
 [[0.07 0.08 0.19

qd = 
 [[  127.92 -1645.06 -3271.17 -2675.14  2679.38 -3927.95]] 


Jp_size =  6
skew = 
 [[-0.23 -0.59  0.27]
 [ 0.05 -0.55  0.9 ]
 [-0.63 -0.67 -0.62]]
vec = 
 [[0.9  0.27 0.59]]
delta_X = 
 [[0.18]
 [0.83]
 [0.25]
 [0.9 ]
 [0.27]
 [0.59]]
np.linalg.norm(delta_X) = 1.42
qd = 
 [[  128.23 -1645.06 -3275.76 -2680.3   2676.97 -3935.  ]] 


Jp_size =  6
skew = 
 [[-1.86  0.49 -0.16]
 [ 0.03 -0.62  0.95]
 [ 0.52  0.79 -1.33]]
vec = 
 [[0.95 0.16 0.49]]
delta_X = 
 [[0.02]
 [0.75]
 [0.16]
 [0.95]
 [0.16]
 [0.49]]
np.linalg.norm(delta_X) = 1.33
qd = 
 [[  135.74 -1648.33 -3289.89 -2675.67  2681.84 -3959.53]] 


Jp_size =  6
skew = 
 [[-1.5  -0.86 -0.03]
 [ 0.73 -1.44  0.52]
 [-0.46  0.24 -0.15]]
vec = 
 [[0.52 0.03 0.86]]
delta_X = 
 [[ 0.32]
 [ 0.75]
 [-0.09]
 [ 0.52]
 [ 0.03]
 [ 0.86]]
np.linalg.norm(delta_X) = 1.3
qd = 
 [[  137.97 -1656.02 -3290.58 -2675.34  2680.64 -3953.19]] 


Jp_size =  6
skew = 
 [[-1.54  0.52 -0.67]
 [-0.13 -0.27  0.67]
 [ 0.83  0.45 -1.32]]
vec = 
 [[0.67 0.67 0.

qd = 
 [[  722.91 -1849.95 -3391.91 -3535.2   3226.7  -4460.5 ]] 


Jp_size =  6
skew = 
 [[-1.99 -0.11  0.02]
 [ 0.04 -1.14  0.99]
 [-0.1   0.98 -0.85]]
vec = 
 [[0.99 0.02 0.11]]
delta_X = 
 [[-0.1 ]
 [ 0.77]
 [-0.15]
 [ 0.99]
 [ 0.02]
 [ 0.11]]
np.linalg.norm(delta_X) = 1.27
qd = 
 [[  729.97 -1847.51 -3380.36 -3534.45  3229.64 -4475.62]] 


Jp_size =  6
skew = 
 [[-0.7   0.69  0.67]
 [-0.24 -1.63  0.75]
 [ 0.93 -0.37 -1.03]]
vec = 
 [[0.75 0.67 0.69]]
delta_X = 
 [[ 0.21]
 [ 1.3 ]
 [-0.09]
 [ 0.75]
 [ 0.67]
 [ 0.69]]
np.linalg.norm(delta_X) = 1.8
qd = 
 [[  724.35 -1857.3  -3364.02 -3531.57  3215.69 -4474.33]] 


Jp_size =  6
skew = 
 [[-1.69 -0.23 -0.68]
 [-0.71 -0.67  0.62]
 [ 0.08  0.91 -1.38]]
vec = 
 [[0.62 0.68 0.23]]
delta_X = 
 [[0.07]
 [0.8 ]
 [0.35]
 [0.62]
 [0.68]
 [0.23]]
np.linalg.norm(delta_X) = 1.29
qd = 
 [[  725.83 -1857.6  -3357.8  -3557.97  3245.83 -4459.39]] 


Jp_size =  6
skew = 
 [[-1.83 -0.04 -0.53]
 [ 0.39 -0.42 -0.7 ]
 [ 0.34 -0.8  -1.48]]
vec = 
 [[0.7  0

qd = 
 [[ 2373.8  -2940.84  -769.89 -3741.07  4194.39 -6939.74]] 


Jp_size =  6
skew = 
 [[-1.05 -0.99  0.03]
 [ 0.01 -1.03 -0.99]
 [ 1.   -0.04 -0.97]]
vec = 
 [[0.99 0.03 0.99]]
delta_X = 
 [[0.23]
 [0.86]
 [0.22]
 [0.99]
 [0.03]
 [0.99]]
np.linalg.norm(delta_X) = 1.67
qd = 
 [[ 2357.31 -2933.85  -651.88 -3747.99  4154.71 -6850.64]] 


Jp_size =  6
skew = 
 [[-1.73 -0.61 -0.28]
 [ 0.68 -1.73 -0.17]
 [-0.1  -0.31 -0.05]]
vec = 
 [[0.17 0.28 0.61]]
delta_X = 
 [[0.21]
 [1.13]
 [0.33]
 [0.17]
 [0.28]
 [0.61]]
np.linalg.norm(delta_X) = 1.38
qd = 
 [[ 2364.72 -2929.18  -644.51 -3737.85  4140.32 -6842.  ]] 


Jp_size =  6
skew = 
 [[-0.72 -0.76  0.59]
 [ 0.47 -1.43 -0.78]
 [ 0.84  0.48 -0.75]]
vec = 
 [[0.78 0.59 0.76]]
delta_X = 
 [[0.02]
 [0.76]
 [0.01]
 [0.78]
 [0.59]
 [0.76]]
np.linalg.norm(delta_X) = 1.45
qd = 
 [[ 2368.55 -2925.24  -646.25 -3735.93  4149.24 -6854.89]] 


Jp_size =  6
skew = 
 [[-1.81 -0.56  0.13]
 [ 0.14 -0.98  0.99]
 [-0.55  0.83 -0.94]]
vec = 
 [[0.99 0.13 0.56]]


qd = 
 [[   988.17  -2608.58  -1093.25  -2752.65   3079.69 -12366.03]] 


Jp_size =  6
skew = 
 [[-0.31 -0.6  -0.4 ]
 [ 0.42 -0.21 -0.46]
 [ 0.59  0.14 -0.2 ]]
vec = 
 [[0.46 0.4  0.6 ]]
delta_X = 
 [[-0.01]
 [ 1.14]
 [-0.36]
 [ 0.46]
 [ 0.4 ]
 [ 0.6 ]]
np.linalg.norm(delta_X) = 1.47
qd = 
 [[   989.31  -2611.05  -1080.12  -2751.96   3077.99 -12367.34]] 


Jp_size =  6
skew = 
 [[-0.96  0.31  0.95]
 [ 0.53 -1.82  0.24]
 [ 0.85  0.5  -1.2 ]]
vec = 
 [[0.24 0.95 0.31]]
delta_X = 
 [[0.5 ]
 [0.58]
 [0.08]
 [0.24]
 [0.95]
 [0.31]]
np.linalg.norm(delta_X) = 1.28
qd = 
 [[   990.68  -2606.74  -1087.58  -2751.06   3079.62 -12360.27]] 


Jp_size =  6
skew = 
 [[-1.66 -0.72 -0.19]
 [-0.61 -0.61  0.69]
 [-0.44  0.56 -1.69]]
vec = 
 [[0.69 0.19 0.72]]
delta_X = 
 [[0.2 ]
 [0.49]
 [0.41]
 [0.69]
 [0.19]
 [0.72]]
np.linalg.norm(delta_X) = 1.22
qd = 
 [[   991.68  -2610.41  -1083.22  -2752.23   3079.38 -12359.59]] 


Jp_size =  6
skew = 
 [[-1.   -0.99  0.02]
 [-0.36 -0.98  0.92]
 [-0.93 -0.01 -1.37

qd = 
 [[   627.79  -2544.15   -786.03  -2520.39   3042.37 -12792.34]] 


Jp_size =  6
skew = 
 [[-1.19 -0.97 -0.07]
 [ 0.75 -1.19  0.63]
 [-0.63  0.08 -0.22]]
vec = 
 [[0.63 0.07 0.97]]
delta_X = 
 [[0.73]
 [0.68]
 [0.19]
 [0.63]
 [0.07]
 [0.97]]
np.linalg.norm(delta_X) = 1.54
qd = 
 [[   606.93  -2545.96   -798.42  -2518.86   3042.18 -12814.82]] 


Jp_size =  6
skew = 
 [[-0.51 -0.72  0.5 ]
 [ 0.87 -0.67 -0.41]
 [ 0.14  0.63 -0.22]]
vec = 
 [[0.41 0.5  0.72]]
delta_X = 
 [[ 0.15]
 [ 0.64]
 [-0.35]
 [ 0.41]
 [ 0.5 ]
 [ 0.72]]
np.linalg.norm(delta_X) = 1.22
qd = 
 [[   608.84  -2544.88   -802.46  -2516.56   3046.3  -12813.78]] 


Jp_size =  6
skew = 
 [[-1.9  -0.11  0.43]
 [-0.25 -0.07 -0.27]
 [-0.36 -0.35 -1.85]]
vec = 
 [[0.27 0.43 0.11]]
delta_X = 
 [[0.54]
 [0.79]
 [0.33]
 [0.27]
 [0.43]
 [0.11]]
np.linalg.norm(delta_X) = 1.14
qd = 
 [[   602.93  -2544.05   -790.17  -2511.29   3032.82 -12814.13]] 


Jp_size =  6
skew = 
 [[-1.72 -0.69 -0.07]
 [-0.56 -0.46  0.63]
 [-0.4   0.5  -1.78

skew = 
 [[-1.21  0.98 -0.03]
 [-0.98 -1.21 -0.03]
 [-0.04  0.03  0.  ]]
vec = 
 [[0.03 0.03 0.98]]
delta_X = 
 [[ 0.14]
 [ 0.44]
 [-0.14]
 [ 0.03]
 [ 0.03]
 [ 0.98]]
np.linalg.norm(delta_X) = 1.09
qd = 
 [[   999.11  -2732.34  -1232.    -2383.56   2570.35 -10347.81]] 


Jp_size =  6
skew = 
 [[-0.65 -0.39 -0.85]
 [ 0.91 -0.65  0.21]
 [ 0.22 -0.85 -0.52]]
vec = 
 [[0.21 0.85 0.39]]
delta_X = 
 [[0.62]
 [1.07]
 [0.29]
 [0.21]
 [0.85]
 [0.39]]
np.linalg.norm(delta_X) = 1.59
qd = 
 [[  1002.4   -2737.98  -1234.4   -2384.46   2572.57 -10356.14]] 


Jp_size =  6
skew = 
 [[-1.98 -0.19  0.06]
 [-0.12 -0.65 -0.92]
 [ 0.15 -0.91 -1.38]]
vec = 
 [[0.92 0.06 0.19]]
delta_X = 
 [[0.26]
 [0.82]
 [0.14]
 [0.92]
 [0.06]
 [0.19]]
np.linalg.norm(delta_X) = 1.28
qd = 
 [[  1007.44  -2747.72  -1214.79  -2391.02   2576.52 -10415.59]] 


Jp_size =  6
skew = 
 [[-1.53  0.58  0.61]
 [ 0.01 -1.72  0.69]
 [ 0.85  0.38 -0.62]]
vec = 
 [[0.69 0.61 0.58]]
delta_X = 
 [[0.11]
 [0.65]
 [0.05]
 [0.69]
 [0.61]
 [0.5

skew = 
 [[-0.54 -0.6  -0.66]
 [ 0.86 -0.54  0.17]
 [ 0.2  -0.64 -0.27]]
vec = 
 [[0.17 0.66 0.6 ]]
delta_X = 
 [[-0.16]
 [ 0.72]
 [ 0.06]
 [ 0.17]
 [ 0.66]
 [ 0.6 ]]
np.linalg.norm(delta_X) = 1.17
qd = 
 [[  1442.21  -2073.13  -2168.61  -3831.54   3309.14 -12989.6 ]] 


Jp_size =  6
skew = 
 [[-1.8   0.38 -0.45]
 [ 0.1  -1.65 -0.73]
 [-0.58 -0.64 -0.51]]
vec = 
 [[0.73 0.45 0.38]]
delta_X = 
 [[-0.08]
 [ 0.71]
 [ 0.09]
 [ 0.73]
 [ 0.45]
 [ 0.38]]
np.linalg.norm(delta_X) = 1.18
qd = 
 [[  1439.96  -2084.72  -2179.55  -3833.92   3302.75 -12975.44]] 


Jp_size =  6
skew = 
 [[-1.52  0.41 -0.75]
 [-0.8  -1.52  0.25]
 [-0.3   0.74 -0.4 ]]
vec = 
 [[0.25 0.75 0.41]]
delta_X = 
 [[0.08]
 [0.76]
 [0.53]
 [0.25]
 [0.75]
 [0.41]]
np.linalg.norm(delta_X) = 1.29
qd = 
 [[  1440.72  -2085.06  -2176.84  -3829.92   3299.94 -12977.79]] 


Jp_size =  6
skew = 
 [[-1.88 -0.36 -0.32]
 [-0.14 -0.18 -0.57]
 [ 0.46 -0.47 -1.76]]
vec = 
 [[0.57 0.32 0.36]]
delta_X = 
 [[0.05]
 [0.86]
 [0.21]
 [0.57]
 [0.32]

qd = 
 [[  4884.08  -7920.17 -13413.12  -4087.49    722.39 -10842.52]] 


Jp_size =  6
skew = 
 [[-0.45 -0.82 -0.09]
 [ 0.08 -0.84 -0.98]
 [ 0.83  0.54 -0.85]]
vec = 
 [[0.98 0.09 0.82]]
delta_X = 
 [[ 0.2 ]
 [ 0.42]
 [-0.01]
 [ 0.98]
 [ 0.09]
 [ 0.82]]
np.linalg.norm(delta_X) = 1.36
qd = 
 [[  4885.11  -7918.74 -13414.21  -4086.44    717.9  -10840.69]] 


Jp_size =  6
skew = 
 [[-1.58 -0.55  0.61]
 [-0.38 -0.17  0.4 ]
 [-0.73  0.01 -1.69]]
vec = 
 [[0.4  0.61 0.55]]
delta_X = 
 [[ 0.38]
 [ 0.73]
 [-0.36]
 [ 0.4 ]
 [ 0.61]
 [ 0.55]]
np.linalg.norm(delta_X) = 1.28
qd = 
 [[  4864.85  -7947.51 -13456.67  -4077.25    693.91 -10913.19]] 


Jp_size =  6
skew = 
 [[-0.78  0.76 -0.62]
 [-0.19 -1.59 -0.79]
 [-0.96  0.29 -0.99]]
vec = 
 [[0.79 0.62 0.76]]
delta_X = 
 [[0.17]
 [0.82]
 [0.27]
 [0.79]
 [0.62]
 [0.76]]
np.linalg.norm(delta_X) = 1.54
qd = 
 [[  4871.52  -7953.56 -13452.95  -4182.42    753.11 -10950.88]] 


Jp_size =  6
skew = 
 [[-1.15 -0.97 -0.2 ]
 [ 0.51 -0.91 -0.85]
 [ 0.85 -0.24

qd = 
 [[  5264.38  -8594.76 -13756.8   -4174.38   1520.84 -11411.82]] 


Jp_size =  6
skew = 
 [[-0.41 -0.79  0.13]
 [-0.32 -1.08  0.95]
 [-0.74 -0.59 -1.3 ]]
vec = 
 [[0.95 0.13 0.79]]
delta_X = 
 [[0.34]
 [0.99]
 [0.09]
 [0.95]
 [0.13]
 [0.79]]
np.linalg.norm(delta_X) = 1.63
qd = 
 [[  5254.79  -8588.87 -13750.92  -4184.82   1526.26 -11418.63]] 


Jp_size =  6
skew = 
 [[-1.02  0.61  0.81]
 [-0.1  -1.8   0.6 ]
 [ 1.   -0.08 -0.92]]
vec = 
 [[0.6  0.81 0.61]]
delta_X = 
 [[0.02]
 [0.82]
 [0.05]
 [0.6 ]
 [0.81]
 [0.61]]
np.linalg.norm(delta_X) = 1.44
qd = 
 [[  5252.05  -8578.46 -13721.33  -4194.14   1514.   -11425.45]] 


Jp_size =  6
skew = 
 [[-0.43 -0.76 -0.32]
 [ 0.34 -1.13  0.93]
 [-0.74 -0.64 -0.81]]
vec = 
 [[0.93 0.32 0.76]]
delta_X = 
 [[ 0.33]
 [ 0.97]
 [-0.36]
 [ 0.93]
 [ 0.32]
 [ 0.76]]
np.linalg.norm(delta_X) = 1.65
qd = 
 [[  5250.78  -8579.56 -13718.97  -4196.96   1514.   -11423.12]] 


Jp_size =  6
skew = 
 [[-1.13 -0.9   0.39]
 [ 0.22 -0.64  0.9 ]
 [-0.97  0.2  -0.84

skew = 
 [[-0.87  0.92 -0.39]
 [-0.05 -1.39 -0.94]
 [-0.99  0.14 -1.  ]]
vec = 
 [[0.94 0.39 0.92]]
delta_X = 
 [[-0.04]
 [ 0.5 ]
 [ 0.06]
 [ 0.94]
 [ 0.39]
 [ 0.92]]
np.linalg.norm(delta_X) = 1.46
qd = 
 [[  7311.44  -8946.11 -15107.45  -4836.84   4684.14 -19232.25]] 


Jp_size =  6
skew = 
 [[-0.62  0.5   0.78]
 [-0.46 -1.64  0.62]
 [ 0.8  -0.6  -1.01]]
vec = 
 [[0.62 0.78 0.5 ]]
delta_X = 
 [[0.14]
 [0.73]
 [0.19]
 [0.62]
 [0.78]
 [0.5 ]]
np.linalg.norm(delta_X) = 1.35
qd = 
 [[  7312.01  -8958.69 -15119.63  -4831.     4677.76 -19246.86]] 


Jp_size =  6
skew = 
 [[-0.98  0.48 -0.89]
 [-0.02 -0.11  0.48]
 [ 1.    0.02 -0.97]]
vec = 
 [[0.48 0.89 0.48]]
delta_X = 
 [[0.21]
 [0.62]
 [0.21]
 [0.48]
 [0.89]
 [0.48]]
np.linalg.norm(delta_X) = 1.31
qd = 
 [[  7335.09  -8961.2  -15131.8   -4849.14   4719.36 -19257.04]] 


Jp_size =  6
skew = 
 [[-1.4   0.67 -0.62]
 [-0.87 -1.07  0.47]
 [ 0.27  0.73 -0.38]]
vec = 
 [[0.47 0.62 0.67]]
delta_X = 
 [[ 0.19]
 [ 0.66]
 [-0.18]
 [ 0.47]
 [ 0.62]


skew = 
 [[-0.32 -0.2  -0.71]
 [ 0.08 -0.03 -0.19]
 [ 0.74  0.07 -0.32]]
vec = 
 [[0.19 0.71 0.2 ]]
delta_X = 
 [[0.17]
 [0.7 ]
 [0.02]
 [0.19]
 [0.71]
 [0.2 ]]
np.linalg.norm(delta_X) = 1.05
qd = 
 [[-11996.38   7355.93 -25110.31 -29866.33  12679.61 -17748.28]] 


Jp_size =  6
skew = 
 [[-1.04 -0.29  0.95]
 [ 0.34 -0.11  0.28]
 [-0.94  0.33 -0.94]]
vec = 
 [[0.28 0.95 0.29]]
delta_X = 
 [[0.41]
 [0.86]
 [0.14]
 [0.28]
 [0.95]
 [0.29]]
np.linalg.norm(delta_X) = 1.41
qd = 
 [[-12017.44   7343.36 -25080.81 -29887.22  12689.04 -17787.97]] 


Jp_size =  6
skew = 
 [[-1.47  0.32 -0.83]
 [ 0.52 -1.66 -0.54]
 [-0.71 -0.69 -0.86]]
vec = 
 [[0.54 0.83 0.32]]
delta_X = 
 [[ 0.12]
 [ 0.92]
 [-0.18]
 [ 0.54]
 [ 0.83]
 [ 0.32]]
np.linalg.norm(delta_X) = 1.41
qd = 
 [[-12018.85   7340.62 -25085.24 -29882.1   12688.71 -17787.94]] 


Jp_size =  6
skew = 
 [[-1.48 -0.88 -0.06]
 [-0.01 -1.07  1.  ]
 [-0.87  0.48 -0.97]]
vec = 
 [[1.   0.06 0.88]]
delta_X = 
 [[0.24]
 [0.94]
 [0.25]
 [1.  ]
 [0.06]
 [0.8

skew = 
 [[-0.39  0.38 -0.7 ]
 [-0.63 -1.3  -0.72]
 [-0.48  0.88 -0.94]]
vec = 
 [[0.72 0.7  0.38]]
delta_X = 
 [[ 0.54]
 [ 1.05]
 [-0.11]
 [ 0.72]
 [ 0.7 ]
 [ 0.38]]
np.linalg.norm(delta_X) = 1.6
qd = 
 [[-12468.88   8062.49 -27061.79 -29940.12  10731.68 -19641.78]] 


Jp_size =  6
skew = 
 [[-1.97 -0.09 -0.24]
 [-0.24 -1.02  0.98]
 [-0.1   0.99 -1.  ]]
vec = 
 [[0.98 0.24 0.09]]
delta_X = 
 [[0.05]
 [0.64]
 [0.6 ]
 [0.98]
 [0.24]
 [0.09]]
np.linalg.norm(delta_X) = 1.34
qd = 
 [[-12496.09   8069.19 -27041.2  -29942.3   10725.54 -20105.59]] 


Jp_size =  6
skew = 
 [[-0.65  0.53  0.78]
 [-0.38 -1.69  0.62]
 [ 0.86 -0.51 -1.04]]
vec = 
 [[0.62 0.78 0.53]]
delta_X = 
 [[-0.06]
 [ 0.72]
 [ 0.42]
 [ 0.62]
 [ 0.78]
 [ 0.53]]
np.linalg.norm(delta_X) = 1.4
qd = 
 [[-12493.93   8073.04 -27046.35 -29944.87  10727.17 -20111.95]] 


Jp_size =  6
skew = 
 [[-1.09  0.84 -0.52]
 [ 0.54 -1.4  -0.74]
 [-0.84 -0.35 -1.41]]
vec = 
 [[0.74 0.52 0.84]]
delta_X = 
 [[0.24]
 [0.76]
 [0.07]
 [0.74]
 [0.52]
 

qd = 
 [[-12947.54   8087.01 -26577.83 -30626.94  11137.2  -24282.61]] 


Jp_size =  6
skew = 
 [[-1.27  0.61 -0.75]
 [ 0.58 -1.51 -0.62]
 [-0.77 -0.6  -1.21]]
vec = 
 [[0.62 0.75 0.61]]
delta_X = 
 [[-0.07]
 [ 1.24]
 [ 0.32]
 [ 0.62]
 [ 0.75]
 [ 0.61]]
np.linalg.norm(delta_X) = 1.72
qd = 
 [[-12949.32   8061.71 -26564.52 -30605.02  11014.81 -24389.29]] 


Jp_size =  6
skew = 
 [[-1.91 -0.14 -0.39]
 [ 0.29 -0.54 -0.84]
 [ 0.29 -0.89 -1.38]]
vec = 
 [[0.84 0.39 0.14]]
delta_X = 
 [[0.35]
 [1.09]
 [0.42]
 [0.84]
 [0.39]
 [0.14]]
np.linalg.norm(delta_X) = 1.54
qd = 
 [[-12671.74   7960.04 -26395.42 -30541.11  10858.32 -25225.46]] 


Jp_size =  6
skew = 
 [[-1.07 -0.78  0.61]
 [-0.87 -1.25 -0.43]
 [ 0.49 -0.56 -1.66]]
vec = 
 [[0.43 0.61 0.78]]
delta_X = 
 [[ 0.08]
 [ 1.2 ]
 [-0.08]
 [ 0.43]
 [ 0.61]
 [ 0.78]]
np.linalg.norm(delta_X) = 1.62
qd = 
 [[-12672.26   7954.15 -26404.8  -30543.03  10851.81 -25217.42]] 


Jp_size =  6
skew = 
 [[-1.12  0.95 -0.26]
 [ 0.33 -0.72  0.89]
 [ 0.94  0.02

qd = 
 [[-13328.88   7661.37 -26931.92 -29112.51  10139.11 -27986.6 ]] 


Jp_size =  6
skew = 
 [[-0.51  0.21  0.85]
 [ 0.42 -1.91 -0.02]
 [ 0.76  0.38 -1.54]]
vec = 
 [[0.02 0.85 0.21]]
delta_X = 
 [[0.16]
 [0.66]
 [0.27]
 [0.02]
 [0.85]
 [0.21]]
np.linalg.norm(delta_X) = 1.14
qd = 
 [[-13334.26   7655.6  -26921.07 -29104.86  10129.61 -27992.15]] 


Jp_size =  6
skew = 
 [[-1.89  0.45  0.13]
 [-0.37 -1.51 -0.77]
 [-0.27 -0.74 -0.38]]
vec = 
 [[0.77 0.13 0.45]]
delta_X = 
 [[ 0.31]
 [ 1.03]
 [-0.1 ]
 [ 0.77]
 [ 0.13]
 [ 0.45]]
np.linalg.norm(delta_X) = 1.41
qd = 
 [[-13321.27   7627.76 -26958.41 -29101.84  10125.87 -28041.5 ]] 


Jp_size =  6
skew = 
 [[-0.36 -0.08  0.76]
 [ 0.4  -1.81 -0.42]
 [ 0.65  0.58 -1.49]]
vec = 
 [[0.42 0.76 0.08]]
delta_X = 
 [[0.32]
 [0.77]
 [0.21]
 [0.42]
 [0.76]
 [0.08]]
np.linalg.norm(delta_X) = 1.22
qd = 
 [[-13337.85   7643.61 -26935.51 -29088.97  10117.74 -28013.65]] 


Jp_size =  6
skew = 
 [[-1.89  0.45 -0.01]
 [-0.14 -1.3  -0.94]
 [-0.43 -0.83 -0.67

qd = 
 [[-13727.92   4785.48 -25440.2  -30190.84   9577.79 -26871.94]] 


Jp_size =  6
skew = 
 [[-0.18  0.53 -0.24]
 [-0.53 -0.46 -0.65]
 [-0.22  0.66 -0.28]]
vec = 
 [[0.65 0.24 0.53]]
delta_X = 
 [[ 0.04]
 [ 0.76]
 [-0.38]
 [ 0.65]
 [ 0.24]
 [ 0.53]]
np.linalg.norm(delta_X) = 1.22
qd = 
 [[-13727.35   4783.25 -25434.87 -30193.48   9575.2  -26877.63]] 


Jp_size =  6
skew = 
 [[-0.75  0.92  0.25]
 [ 0.31 -1.32  0.88]
 [ 0.92 -0.15 -1.37]]
vec = 
 [[0.88 0.25 0.92]]
delta_X = 
 [[0.03]
 [1.01]
 [0.57]
 [0.88]
 [0.25]
 [0.92]]
np.linalg.norm(delta_X) = 1.74
qd = 
 [[-13725.24   4780.64 -25433.86 -30186.61   9568.95 -26880.31]] 


Jp_size =  6
skew = 
 [[-0.05  0.14  0.3 ]
 [ 0.31 -1.15 -0.95]
 [-0.09  0.98 -1.18]]
vec = 
 [[0.95 0.3  0.14]]
delta_X = 
 [[-0.13]
 [ 0.52]
 [-0.24]
 [ 0.95]
 [ 0.3 ]
 [ 0.14]]
np.linalg.norm(delta_X) = 1.16
qd = 
 [[-13724.49   4779.53 -25433.93 -30186.11   9570.23 -26883.37]] 


Jp_size =  6
skew = 
 [[-0.62 -0.55 -0.73]
 [ 0.3  -1.68  0.66]
 [-0.88 -0.47

qd = 
 [[-13575.32   4841.25 -24394.75 -30691.25  11133.78 -23615.75]] 


Jp_size =  6
skew = 
 [[-0.91 -0.02 -1.  ]
 [-0.87 -0.51 -0.09]
 [ 0.49  0.88 -0.98]]
vec = 
 [[0.09 1.   0.02]]
delta_X = 
 [[0.22]
 [0.62]
 [0.01]
 [0.09]
 [1.  ]
 [0.02]]
np.linalg.norm(delta_X) = 1.2
qd = 
 [[-13571.76   4847.88 -24404.98 -30678.34  11118.75 -23612.41]] 


Jp_size =  6
skew = 
 [[-1.29  0.62  0.72]
 [ 0.94 -0.95  0.34]
 [ 0.18  0.78 -1.6 ]]
vec = 
 [[0.34 0.72 0.62]]
delta_X = 
 [[-0.1 ]
 [ 0.92]
 [ 0.21]
 [ 0.34]
 [ 0.72]
 [ 0.62]]
np.linalg.norm(delta_X) = 1.39
qd = 
 [[-13570.95   4842.84 -24412.9  -30675.48  11126.22 -23616.69]] 


Jp_size =  6
skew = 
 [[-1.5  -0.75  0.39]
 [ 0.68 -1.63 -0.34]
 [ 0.51  0.1  -0.16]]
vec = 
 [[0.34 0.39 0.75]]
delta_X = 
 [[-0.04]
 [ 0.81]
 [ 0.02]
 [ 0.34]
 [ 0.39]
 [ 0.75]]
np.linalg.norm(delta_X) = 1.22
qd = 
 [[-13573.89   4845.86 -24420.76 -30674.24  11123.11 -23614.79]] 


Jp_size =  6
skew = 
 [[-0.05 -0.07  0.28]
 [-0.18 -0.4   0.78]
 [-0.22 -0.79 

skew = 
 [[-1.11 -0.52 -0.84]
 [-0.16 -0.15 -0.5 ]
 [ 0.98  0.08 -1.19]]
vec = 
 [[0.5  0.84 0.52]]
delta_X = 
 [[0.16]
 [0.66]
 [0.44]
 [0.5 ]
 [0.84]
 [0.52]]
np.linalg.norm(delta_X) = 1.37
qd = 
 [[-13645.96   3795.79 -23135.85 -30675.18   9726.21 -24705.09]] 


Jp_size =  6
skew = 
 [[-0.8   0.75 -0.62]
 [ 0.33 -0.45  0.76]
 [ 0.92 -0.37 -1.14]]
vec = 
 [[0.76 0.62 0.75]]
delta_X = 
 [[0.23]
 [1.33]
 [0.23]
 [0.76]
 [0.62]
 [0.75]]
np.linalg.norm(delta_X) = 1.84
qd = 
 [[-13645.06   3794.81 -23127.46 -30681.83   9764.78 -24732.35]] 


Jp_size =  6
skew = 
 [[-0.9  -0.44 -0.9 ]
 [ 0.29 -0.13 -0.39]
 [ 0.95 -0.23 -0.79]]
vec = 
 [[0.39 0.9  0.44]]
delta_X = 
 [[-0.16]
 [ 1.21]
 [ 0.25]
 [ 0.39]
 [ 0.9 ]
 [ 0.44]]
np.linalg.norm(delta_X) = 1.65
qd = 
 [[-13617.61   3800.24 -22952.45 -30677.91   9782.61 -24605.89]] 


Jp_size =  6
skew = 
 [[-1.08 -0.67  0.76]
 [ 0.5  -0.37  0.6 ]
 [-0.86  0.42 -0.71]]
vec = 
 [[0.6  0.76 0.67]]
delta_X = 
 [[ 0.32]
 [ 0.66]
 [-0.34]
 [ 0.6 ]
 [ 0.76]


qd = 
 [[-12732.1    2308.01 -25218.88 -29326.78  10658.47 -29346.34]] 


Jp_size =  6
skew = 
 [[-0.47 -0.35  0.77]
 [-0.18 -1.93 -0.29]
 [ 0.82  0.01 -1.56]]
vec = 
 [[0.29 0.77 0.35]]
delta_X = 
 [[0.45]
 [1.  ]
 [0.27]
 [0.29]
 [0.77]
 [0.35]]
np.linalg.norm(delta_X) = 1.44
qd = 
 [[-12740.03   2298.16 -25224.99 -29331.28  10629.63 -29369.62]] 


Jp_size =  6
skew = 
 [[-0.22 -0.27 -0.58]
 [-0.5  -1.8  -0.32]
 [-0.38  0.54 -1.76]]
vec = 
 [[0.32 0.58 0.27]]
delta_X = 
 [[-0.02]
 [ 0.95]
 [ 0.09]
 [ 0.32]
 [ 0.58]
 [ 0.27]]
np.linalg.norm(delta_X) = 1.19
qd = 
 [[-12741.29   2292.66 -25225.5  -29334.1   10631.23 -29376.03]] 


Jp_size =  6
skew = 
 [[-0.64  0.65  0.67]
 [-0.29 -1.61  0.74]
 [ 0.89 -0.46 -1.02]]
vec = 
 [[0.74 0.67 0.65]]
delta_X = 
 [[0.21]
 [1.22]
 [0.  ]
 [0.74]
 [0.67]
 [0.65]]
np.linalg.norm(delta_X) = 1.72
qd = 
 [[-12739.8    2285.96 -25221.05 -29333.62  10621.53 -29372.99]] 


Jp_size =  6
skew = 
 [[-0.15 -0.49 -0.19]
 [ 0.08 -1.25  0.97]
 [-0.52 -0.84 -1.17

qd = 
 [[-12324.02   1595.78 -25253.12 -29468.23  10578.67 -28633.73]] 


Jp_size =  6
skew = 
 [[-0.03  0.19 -0.14]
 [ 0.23 -1.74  0.64]
 [ 0.03 -0.65 -1.76]]
vec = 
 [[0.64 0.14 0.19]]
delta_X = 
 [[-0.13]
 [ 0.62]
 [-0.05]
 [ 0.64]
 [ 0.14]
 [ 0.19]]
np.linalg.norm(delta_X) = 0.93
qd = 
 [[-12323.99   1590.92 -25259.12 -29468.38  10583.11 -28634.57]] 


Jp_size =  6
skew = 
 [[-1.31 -0.62 -0.73]
 [ 0.   -0.23 -0.65]
 [ 0.95 -0.2  -1.25]]
vec = 
 [[0.65 0.73 0.62]]
delta_X = 
 [[-0.03]
 [ 0.67]
 [ 0.55]
 [ 0.65]
 [ 0.73]
 [ 0.62]]
np.linalg.norm(delta_X) = 1.45
qd = 
 [[-12324.28   1590.78 -25261.41 -29469.97  10582.71 -28636.75]] 


Jp_size =  6
skew = 
 [[-0.36 -0.29 -0.73]
 [ 0.14 -1.87  0.48]
 [-0.77 -0.4  -1.51]]
vec = 
 [[0.48 0.73 0.29]]
delta_X = 
 [[0.29]
 [0.77]
 [0.08]
 [0.48]
 [0.73]
 [0.29]]
np.linalg.norm(delta_X) = 1.24
qd = 
 [[-12316.57   1594.43 -25255.38 -29478.94  10588.78 -28620.24]] 


Jp_size =  6
skew = 
 [[-1.95 -0.03  0.33]
 [-0.31 -1.16 -0.94]
 [ 0.08 -0.99

KeyboardInterrupt: 

In [ ]:
# gripper 

#yum_gripper_handle = sim.getObjectHandle("openCloseJoint")

connector=sim.getObject('./attachPoint')
objectSensor=sim.getObject('./attachProxSensor')

#Target_Object_handle = 


index=0
while True: 
    
    shape=sim.getObjects(index,sim.object_shape_type)
    
    if shape==-1:
        break
        
    cond_1 = sim.getObjectInt32Param(shape,sim.shapeintparam_static)
    cond_2 = sim.getObjectInt32Param(shape,sim.shapeintparam_respondable)
    cond_3 = sim.checkProximitySensor(objectSensor,shape)
    
    if ((cond_1==0) and (cond_2!=0) and (cond_3==1)):
         # Ok, we found a non-static respondable shape that was detected
        attachedShape=shape
         # Do the connection:
        sim.setObjectParent(attachedShape,connector,true)
        break
    index +=1


# c) And just before opening the gripper again, detach the previously attached shape:
#sim.setObjectParent(attachedShape,-1,true)


In [13]:
print(q0)
print(qd)

[[ 48311.15 -12324.62 -58170.31  32275.45 -83880.68  29207.89]]
[[ 48311.15 -12324.62 -58170.31  32275.45 -83880.68  29207.89]]


In [ ]:

client.setStepping(False)
sim.startSimulation()


for (handle,degree) in zip(joint_handels,qd[0]):
    sim.startSimulation()
#     # close
#     sim.setJointTargetVelocity(yum_gripper_handle,-0.02)
    sim.setJointTargetPosition(handle, degree ) # degree by radian
    

In [ ]:
#open
#sim.setJointTargetVelocity(yum_gripper_handle,0.02)

In [ ]:
sim.stopSimulation()