In [1]:
import time
import numpy as np 
from zmqRemoteApi import RemoteAPIClient
# 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

In [2]:
def degree_To_radian(degree):
    return (degree * np.pi/180)

# def FK(th,alp,a,d):
#     Cth=np.cos(th)
#     Sth=np.sin(th)
#     Calp=np.cos(alp)
#     Salp=np.sin(alp)
#     T=np.array([[Cth, -Sth*Calp, Sth*Salp, a*Cth],[Sth, Cth*Calp, -Cth*Salp , a*Sth],[0,Salp,Calp,d],[0,0,0,1]])
#     return np.round(T,2)

def FK(th,alp,a,d):
    
    Cth=np.cos(th)
    Sth=np.sin(th)
    Calp=np.cos(alp)
    Salp=np.sin(alp)
    
    T=np.array([
                    [Cth, -Sth*Calp, Sth*Salp, a*Cth],
                    [Sth, Cth*Calp, -Cth*Salp , a*Sth],
                    [0,Salp,Calp,d],
                    [0,0,0,1]
               ])
    return np.round(T.reshape(4,4),2)


In [3]:
def Calculate_Jacopian_P(Trans_mat_arr):
    
    O_0 = np.zeros([3,1])
    Jp_size = len(Trans_mat_arr)
    Z_0 = np.array([[0,0,1]]).reshape(3,1)
    
    Z_arr = [z[0:3,2] for z in Trans_mat_arr]
    Z_arr.insert(0,Z_0)
    
    O_arr = [o[0:3,3] for o in Trans_mat_arr]
    O_arr.insert(0,O_0)
    
    O_last = O_arr[-1].reshape(3,1)
    
    jp_mat = np.array([
        [np.cross(Z_arr[i].reshape(3,1),(O_last-O_arr[i].reshape(3,1)),axis=0) for i in range(Jp_size)]
    ])
        
    return jp_mat.reshape(3,Jp_size).transpose()
    
def Calculate_Jacopian_r(Trans_mat_arr):
    
    Z_0 = np.array([[0,0,1]])
    Jp_size = len(Trans_mat_arr)
        
    Z_arr = [Trans_mat_arr[z][0:3,2] for z in range(Jp_size-1)]
    Z_arr.insert(0,Z_0)
    
    Jr_mat = np.array([[z.reshape(3,1) for z in Z_arr]])
    
    return Jr_mat.reshape(3,Jp_size).transpose()

def Calculate_J(Trans_mat_arr):
    J_size = len(Trans_mat_arr)
    J = np.array([
                    [Calculate_Jacopian_P(Trans_mat_arr),
                     Calculate_Jacopian_r(Trans_mat_arr)]
                ])
    
    return J.reshape(6,J_size)
    

In [4]:
def Calculate_0n_Matrix(Trans_mat_arr):
    
    n = len(Trans_mat_arr)
    T_0 = np.identity(4)
    
    result_mat = []
    
    for i in range(n):
        T_0 = np.matmul(T_0,Trans_mat_arr[i])
        result_mat.append(T_0)
        
    return result_mat
    

In [5]:
def Calculate_Delta_X(Td, T0):
    
    Pd = Td[0:3,3]
    P0 = T0[0:3,3]
    
    Rd = Td[0:3,0:3]
    R0 = T0[0:3,0:3]
    
    I = np.identity(3)
    
    Pos_list = np.array([[d-c for d,c in zip(Pd,P0)]])
    Pos_list = Pos_list.reshape(3,1)
    
    DR = np.matmul(Rd,R0.transpose())
    skew = np.subtract(DR , I)
    
    vec = np.array([[abs(skew[1,2]),abs(skew[0,2]) ,abs(skew[0,1])]])
    vec = vec.reshape(3,1)
    
    Delta_X = np.array([Pos_list,vec])
    
#     print("Delta_X = \n",Delta_X)
    
    return Delta_X.reshape(6,1)  

In [23]:
def Calculate_IK(dX,J,q0):
    # qd = q0 + J+ * d_X
    
    j_transpose = J.transpose()
    j_jT_inv = np.linalg.inv( np.matmul(J,j_transpose) ) 
    
    j_pinv = np.matmul(j_transpose,j_jT_inv)
    
    temp = np.add(q0,np.matmul(np.round(j_pinv,2),dX))
    
    print("j_pinv = \n",j_pinv)
    print("temp = \n",temp)
    
    qd = [the[0] for the in temp]
    
    return np.round(qd,2)

In [68]:
error = 0.9
q0 = [0,0,0,0,0,0]
alpha = [90,0,0,90,270,0]
D = [0.1519,0,0,0.11235,0.08535,0.0819]
A = [0,-0.24365,-0.21325,0,0,0]

# calc Transformation matrix using FK
Trans_list = [FK(degree_To_radian(theta),degree_To_radian(alp),a,d) for theta,alp,d,a in zip(q0,alpha,D,A)]

T_0n = Calculate_0n_Matrix(Trans_list)
T_d = FK(degree_To_radian(45),degree_To_radian(45),0,0)
# print(T_d)

# claculate Jacopian matrix
J = Calculate_J(T_0n)

# calculate delta X matrix  
delta_X = Calculate_Delta_X(T_0n[0],T_0n[-1])

# calculate qd using IK 
qd = Calculate_IK(delta_X,J,q0)

print("qd = \n",qd,"\n\n")

j_pinv = 
 [[ 0.5         2.375       0.25        0.22265625  0.375      -0.453125  ]
 [ 0.25       -4.8125     -0.75       -0.42578125  0.          0.        ]
 [-0.5         2.375       0.5         0.2109375  -0.4375     -0.515625  ]
 [ 0.204329    0.06738817 -2.57085137 -0.00681006  0.03941558 -0.0322619 ]
 [-0.0625     -0.0234375  -0.0625     -1.00097656 -0.0078125  -0.01171875]
 [ 0.          0.          0.          0.          0.          0.        ]]
temp = 
 [[ 0.6997  0.6997  0.6997  0.6997  0.6997  0.6997]
 [-0.8689 -0.8689 -0.8689 -0.8689 -0.8689 -0.8689]
 [ 0.2722  0.2722  0.2722  0.2722  0.2722  0.2722]
 [-0.128  -0.128  -0.128  -0.128  -0.128  -0.128 ]
 [-0.0362 -0.0362 -0.0362 -0.0362 -0.0362 -0.0362]
 [ 0.      0.      0.      0.      0.      0.    ]]
qd = 
 [ 0.7  -0.87  0.27 -0.13 -0.04  0.  ] 




In [74]:
counter = 0
while np.round(np.linalg.norm(delta_X),2) < error:
    
    q0 = qd.copy()


    Trans_list.clear()
    
    Trans_list = [FK(degree_To_radian(theta),degree_To_radian(alp),a,d) for theta,alp,d,a in zip(q0,alpha,D,A)]
    
    T_0n = Calculate_0n_Matrix(Trans_list)
    J = Calculate_J(T_0n)
    delta_X = Calculate_Delta_X(T_0n[0],T_0n[-1])
    
    print("delta_X = \n",delta_X)
    print("np.linalg.norm(delta_X) =",np.round(np.linalg.norm(delta_X),2))
    
    qd = Calculate_IK(delta_X,J,q0)
    print("qd = \n",qd,"\n\n")
    counter+=1
    

delta_X = 
 [[4.49900e-01]
 [1.94518e-01]
 [8.58000e-02]
 [2.00000e-04]
 [2.00000e-02]
 [0.00000e+00]]
np.linalg.norm(delta_X) = 0.5
j_pinv = 
 [[ 2.28049481e+00  2.67714659e+00 -1.75817180e+00  2.47938867e-01
   1.87398362e-01 -3.70512861e-01]
 [ 4.30759113e-02 -4.73946997e+00 -9.42970972e-01 -4.24868333e-01
  -5.05129376e-03  2.51867726e-03]
 [-2.32357072e+00  2.06232338e+00  2.70114277e+00  1.76929467e-01
  -1.82347068e-01 -6.32005816e-01]
 [ 3.86235421e-03 -4.05242353e-03 -2.21775422e+00  3.63476941e-03
   3.81683723e-04 -7.69851977e-04]
 [ 1.39012059e-01 -7.63607858e-02 -1.53113030e-01 -1.00656767e+00
  -9.01038872e-03  1.78985880e-02]
 [-4.60549427e+02 -6.14019075e+01  4.48302324e+02 -6.09800710e+00
   6.30340857e+01 -2.61664243e+01]]
temp = 
 [[ 2.09992224e+00  5.29922240e-01  1.66992224e+00  1.26992224e+00
   1.35992224e+00  1.39992224e+00]
 [-2.84955320e-01 -1.85495532e+00 -7.14955320e-01 -1.11495532e+00
  -1.02495532e+00 -9.84955320e-01]
 [ 2.85035080e-01 -1.28496492e+00 -1.4

In [75]:
client = RemoteAPIClient()
sim = client.getObject('sim')

# When simulation is not running, ZMQ message handling could be a bit
# slow, since the idle loop runs at 8 Hz by default. So let's make
# sure that the idle loop runs at full speed for this program:
defaultIdleFps = sim.getInt32Param(sim.intparam_idle_fps)
sim.setInt32Param(sim.intparam_idle_fps, 0)

1

In [76]:
# set Object name 
joint_names = [f"joint_{i+1}"  for i in range(6)]
# set Object handel 
joint_handels = [sim.getObjectHandle(joint) for joint in joint_names]
joint_Position = [sim.getJointPosition(handle) for handle in joint_handels]

for handle in joint_handels:
    sim.setObjectInt32Parameter(handle ,2001,~0) #to enable the position control

In [80]:
client.setStepping(False)
sim.startSimulation()

for (handle,degree) in zip(joint_handels,qd):
    sim.setJointTargetPosition(handle,degree) # degree by radian
    sim.startSimulation()

In [79]:
sim.stopSimulation()

1